source 'https://rubygems.org'

ruby '2.4.0'

gem 'bundler'
gem 'foreman'
gem 'rake'
gem 'puma'
gem 'rack-timeout'
gem 'sinatra', '~>2.0.0'
gem 'sinatra-contrib'
gem 'haml'
gem 'sass'
gem 'rack-flash3'
gem 'rack-ssl'
gem 'rack-rewrite'
gem 'mongoid'
gem 'ruby-trello'
gem 'business_time'
gem 'require_all'

group :development do
  gem 'pry'
  gem 'sinatra-reloader'
end

group :development, :test do
  gem 'dotenv'
  gem 'rspec'
  gem 'rspec-its'
#  gem 'cucumber'
#  gem 'capybara'
  gem 'rack_session_access'
#  gem 'capybara-webkit'
  gem 'chronic'
  gem 'launchy'
  gem 'site_prism'
  gem 'page_navigation'
#  gem 'selenium-webdriver'
  gem 'factory_girl'
  gem 'activesupport'
  gem 'faker'
  gem 'timecop'
  gem 'rerun'
end
